var jade = require("jadum/runtime");
module.exports = function index(locals) {
var jade_debug = [{ lineno: 1, filename: "views/home/index.jade" }];
try {
var buf = [];
var jade_mixins = {};
var jade_interp;
;var locals_for_with = (locals || {});(function (require, undefined) {
jade_debug.unshift({ lineno: 0, filename: "views/home/index.jade" });
jade_debug.unshift({ lineno: 1, filename: "views/home/index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 2, filename: "views/home/index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 3, filename: "views/home/index.jade" });
buf.push("<div class=\"sd-u-align--center\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: undefined, filename: "views/home/index.jade" });
buf.push(require("../partials/flash").call(this, locals));
jade_debug.shift();
jade_debug.unshift({ lineno: undefined, filename: "views/home/index.jade" });
buf.push(require("../partials/home_header").call(this, locals));
jade_debug.shift();
jade_debug.unshift({ lineno: 6, filename: "views/home/index.jade" });
buf.push("<main class=\"sd-o-main\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 7, filename: "views/home/index.jade" });
buf.push("<form name=\"loginForm\" action=\"/api/user/login\" method=\"post\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 8, filename: "views/home/index.jade" });
buf.push("<div>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 9, filename: "views/home/index.jade" });
buf.push("<label for=\"username\" class=\"sd-c-form__label--medium\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 9, filename: jade_debug[0].filename });
buf.push("username:");
jade_debug.shift();
jade_debug.shift();
buf.push("</label>");
jade_debug.shift();
jade_debug.unshift({ lineno: 10, filename: "views/home/index.jade" });
buf.push("<input id=\"username\" name=\"username\" type=\"text\" placeholder=\"username\" required=\"required\" class=\"sd-t-wire sd-t-wire--field sd-c-form__field--medium\"/>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 11, filename: "views/home/index.jade" });
buf.push("<div>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 12, filename: "views/home/index.jade" });
buf.push("<label for=\"email\" class=\"sd-c-form__label--medium\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 12, filename: jade_debug[0].filename });
buf.push("email:");
jade_debug.shift();
jade_debug.shift();
buf.push("</label>");
jade_debug.shift();
jade_debug.unshift({ lineno: 13, filename: "views/home/index.jade" });
buf.push("<input id=\"email\" name=\"email\" type=\"email\" placeholder=\"email\" required=\"required\" class=\"sd-t-wire sd-t-wire--field sd-c-form__field--medium\"/>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 14, filename: "views/home/index.jade" });
buf.push("<div>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 15, filename: "views/home/index.jade" });
buf.push("<button type=\"submit\" class=\"sd-c-btn sd-t-wire sd-t-wire-hover sd-t-wire--field sd-c-btn\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 15, filename: jade_debug[0].filename });
buf.push("Login");
jade_debug.shift();
jade_debug.shift();
buf.push("</button>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 16, filename: "views/home/index.jade" });
buf.push("<div>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 17, filename: "views/home/index.jade" });
buf.push("<a href=\"/about\" aria-label=\"About\" class=\"sd-t-wire sd-u-align--center\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 17, filename: jade_debug[0].filename });
buf.push("New to ScribDen?");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 18, filename: "views/home/index.jade" });
buf.push("<div>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 19, filename: "views/home/index.jade" });
buf.push("<a href=\"/register\" aria-label=\"Register\" class=\"sd-t-link sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 19, filename: jade_debug[0].filename });
buf.push("Sign up.");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 20, filename: "views/home/index.jade" });
buf.push("<div>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 21, filename: "views/home/index.jade" });
buf.push("<a href=\"/recent\" aria-label=\"Browse\" class=\"sd-t-link sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 21, filename: jade_debug[0].filename });
buf.push("Or browse.");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</form>");
jade_debug.shift();
jade_debug.shift();
buf.push("</main>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();}.call(this,"require" in locals_for_with?locals_for_with.require:typeof require!=="undefined"?require:undefined,"undefined" in locals_for_with?locals_for_with.undefined:typeof undefined!=="undefined"?undefined:undefined));;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade_debug[0].filename, jade_debug[0].lineno, "//- each action can have its own partial view, and use a model to alter the rendered HTML\n//- http://taunus.bevacqua.io/getting-started#using-jade-as-your-view-engine\ndiv.sd-u-align--center\n  include ../partials/flash\n  include ../partials/home_header\n  main.sd-o-main\n    form(name='loginForm' action='/api/user/login' method='post')\n      div\n        label.sd-c-form__label--medium(for='username') username:\n        input.sd-t-wire.sd-t-wire--field.sd-c-form__field--medium(id='username' name='username' type='text' placeholder='username' required)\n      div\n        label.sd-c-form__label--medium(for='email') email:\n        input.sd-t-wire.sd-t-wire--field.sd-c-form__field--medium(id='email' name='email' type='email' placeholder='email' required)\n      div\n        button.sd-c-btn.sd-t-wire.sd-t-wire-hover.sd-t-wire--field.sd-c-btn(type='submit') Login\n      div\n        a.sd-t-wire.sd-u-align--center(href='/about', aria-label='About') New to ScribDen?\n      div\n        a.sd-t-link.sd-t-wire(href='/register', aria-label='Register') Sign up.\n      div\n        a.sd-t-link.sd-t-wire(href='/recent', aria-label='Browse') Or browse.");
}
}