var jade = require("jadum/runtime");
module.exports = function tos(locals) {
var jade_debug = [{ lineno: 1, filename: "views/home/tos.jade" }];
try {
var buf = [];
var jade_mixins = {};
var jade_interp;
;var locals_for_with = (locals || {});(function (require, undefined) {
jade_debug.unshift({ lineno: 0, filename: "views/home/tos.jade" });
jade_debug.unshift({ lineno: 1, filename: "views/home/tos.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 2, filename: "views/home/tos.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 3, filename: "views/home/tos.jade" });
buf.push("<div class=\"sd-u-align--center\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: undefined, filename: "views/home/tos.jade" });
buf.push(require("../partials/flash").call(this, locals));
jade_debug.shift();
jade_debug.unshift({ lineno: undefined, filename: "views/home/tos.jade" });
buf.push(require("../partials/home_header").call(this, locals));
jade_debug.shift();
jade_debug.unshift({ lineno: 6, filename: "views/home/tos.jade" });
buf.push("<main class=\"sd-o-main sd-o-frame-content\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 7, filename: "views/home/tos.jade" });
buf.push("<article>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 8, filename: "views/home/tos.jade" });
buf.push("<h2 class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 8, filename: jade_debug[0].filename });
buf.push("Terms of Service");
jade_debug.shift();
jade_debug.shift();
buf.push("</h2>");
jade_debug.shift();
jade_debug.unshift({ lineno: 9, filename: "views/home/tos.jade" });
buf.push("<section class=\"sd-u-align--left\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 10, filename: "views/home/tos.jade" });
buf.push("<h3 class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 10, filename: jade_debug[0].filename });
buf.push("I. ACCEPTANCE OF TERMS");
jade_debug.shift();
jade_debug.shift();
buf.push("</h3>");
jade_debug.shift();
jade_debug.unshift({ lineno: 11, filename: "views/home/tos.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 11, filename: jade_debug[0].filename });
buf.push("Hexelberry Studios, ScribDen.com, (\"ScribDen\" or \"Service\") provides the following service to you (\"You\" or \"User\"), subject to these Terms of Service (\"TOS\"), which may be updated periodically without prior notice. BY COMPLETING THE REGISTRATION PROCESS AND/OR USING THE SERVICE YOU HEREBY AGREE THAT YOU ARE ELIGIBLE FOR A SCRIBDEN ACCOUNT AND ARE BOUND BY THESE TERMS AND CONDITIONS, AS DESCRIBED BELOW. Your use of the Service implies your consent to the TOS. It is your responsibility to check if there have been changes to the TOS. Failure to comply with these TOS may result in account suspension, or account deletion at any time, without prior notice.");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift({ lineno: 12, filename: "views/home/tos.jade" });
buf.push("<section class=\"sd-u-align--left\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 13, filename: "views/home/tos.jade" });
buf.push("<h3 class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 13, filename: jade_debug[0].filename });
buf.push("II. YOUR REGISTRATION OBLIGATIONS");
jade_debug.shift();
jade_debug.shift();
buf.push("</h3>");
jade_debug.shift();
jade_debug.unshift({ lineno: 14, filename: "views/home/tos.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 14, filename: jade_debug[0].filename });
buf.push("Account registration is required in order to create a ScribDen account. During registration, all users are required to provide accurate, complete, and current information about themselves in all required fields. Should any of your own information change after submitting it to ScribDen, you are required to update that information as soon as possible. Should ScribDen suspect that your personal information is not complete, current, or accurate, your Account may be suspended or terminated without further notice. ScribDen is committed to being a safe and secure environment for all its users. You must be at least 13 years of age to use the Service. Users who are found to be under 13 years of age may be suspended from the Service without notice.");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift({ lineno: 15, filename: "views/home/tos.jade" });
buf.push("<section class=\"sd-u-align--left\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 16, filename: "views/home/tos.jade" });
buf.push("<h3 class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 16, filename: jade_debug[0].filename });
buf.push("III. SCRIBDEN.COM PRIVACY POLICY");
jade_debug.shift();
jade_debug.shift();
buf.push("</h3>");
jade_debug.shift();
jade_debug.unshift({ lineno: 17, filename: "views/home/tos.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 17, filename: jade_debug[0].filename });
buf.push("Your use of the Service is subject to ScribDen’s privacy policy. For information on ScribDen’s privacy practices, please see the entire privacy policy at ");
jade_debug.shift();
jade_debug.unshift({ lineno: 18, filename: "views/home/tos.jade" });
buf.push("<a href=\"/privacy\" class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 18, filename: jade_debug[0].filename });
buf.push("http://www.scribden.com/privacy.");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift({ lineno: 19, filename: "views/home/tos.jade" });
buf.push("<section class=\"sd-u-align--left\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 20, filename: "views/home/tos.jade" });
buf.push("<h3 class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 20, filename: jade_debug[0].filename });
buf.push("IV. INDEMNITY");
jade_debug.shift();
jade_debug.shift();
buf.push("</h3>");
jade_debug.shift();
jade_debug.unshift({ lineno: 21, filename: "views/home/tos.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 21, filename: jade_debug[0].filename });
buf.push("You agree to indemnify and hold ScribDen, and its subsidiaries, affiliates, officers, agents, co-branders or other partners, and employees, harmless from any alleged claim or demand, including reasonable attorney fees, made by any third party due to or arising out of your Content, your use of the Service, your connection to the Service, your violation of the TOS, or your violation of any rights of others, whether you are a registered user or not. The user is solely responsible for their actions when using the Service, including, but not limited to, costs incurred for Internet access.");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift({ lineno: 22, filename: "views/home/tos.jade" });
buf.push("<section class=\"sd-u-align--left\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 23, filename: "views/home/tos.jade" });
buf.push("<h3 class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 23, filename: jade_debug[0].filename });
buf.push("V. SPECIAL ADMONITIONS FOR INTERNATIONAL USE");
jade_debug.shift();
jade_debug.shift();
buf.push("</h3>");
jade_debug.shift();
jade_debug.unshift({ lineno: 24, filename: "views/home/tos.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 24, filename: jade_debug[0].filename });
buf.push("Recognizing the global nature of the Internet, you agree to comply with all local laws regarding online conduct and acceptable Content. Specifically, you agree to comply with all applicable laws regarding the transmission of technical data exported from the United States and the country in which you reside.");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift({ lineno: 25, filename: "views/home/tos.jade" });
buf.push("<section class=\"sd-u-align--left\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 26, filename: "views/home/tos.jade" });
buf.push("<h3 class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 26, filename: jade_debug[0].filename });
buf.push("VI. GENERAL PRACTICES REGARDING USE AND STORAGE");
jade_debug.shift();
jade_debug.shift();
buf.push("</h3>");
jade_debug.shift();
jade_debug.unshift({ lineno: 27, filename: "views/home/tos.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 27, filename: jade_debug[0].filename });
buf.push("You acknowledge that ScribDen may be required to send you emails regarding your use of the Service. ScribDen will never ask you to submit personal information or verify your Account information in the form of an email. Should you receive any such communications, please do not respond, and forward it to admin@scribden.com at once.");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift({ lineno: 28, filename: "views/home/tos.jade" });
buf.push("<section class=\"sd-u-align--left\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 29, filename: "views/home/tos.jade" });
buf.push("<h3 class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 29, filename: jade_debug[0].filename });
buf.push("VII. MODIFICATIONS TO SERVICE");
jade_debug.shift();
jade_debug.shift();
buf.push("</h3>");
jade_debug.shift();
jade_debug.unshift({ lineno: 30, filename: "views/home/tos.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 30, filename: jade_debug[0].filename });
buf.push("ScribDen reserves the right to modify or discontinue, temporarily or permanently, the Service (or any part thereof) with or without notice at any time. You agree that ScribDen shall not be held liable to you or to any third party for any modification, suspension, or discontinuance of the Service.");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift({ lineno: 31, filename: "views/home/tos.jade" });
buf.push("<section class=\"sd-u-align--left\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 32, filename: "views/home/tos.jade" });
buf.push("<h3 class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 32, filename: jade_debug[0].filename });
buf.push("VIII. NO RESALE OF SERVICE");
jade_debug.shift();
jade_debug.shift();
buf.push("</h3>");
jade_debug.shift();
jade_debug.unshift({ lineno: 33, filename: "views/home/tos.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 33, filename: jade_debug[0].filename });
buf.push("You agree not to reproduce, duplicate, copy, sell, resell, or exploit any portion of the Service, use of the Service, or access to the Service.");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift({ lineno: 34, filename: "views/home/tos.jade" });
buf.push("<section class=\"sd-u-align--left\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 35, filename: "views/home/tos.jade" });
buf.push("<h3 class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 35, filename: jade_debug[0].filename });
buf.push("IX. TERMINATION");
jade_debug.shift();
jade_debug.shift();
buf.push("</h3>");
jade_debug.shift();
jade_debug.unshift({ lineno: 36, filename: "views/home/tos.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 36, filename: jade_debug[0].filename });
buf.push("By using the ScribDen service, you hereby acknowledge and agree that ScribDen may, at its sole discretion, block, restrict, or terminate access; suspend or delete any Account; and flag or remove any Content found within the Service, for any reason, at any time, without prior notice.");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 37, filename: "views/home/tos.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 38, filename: "views/home/tos.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 38, filename: jade_debug[0].filename });
buf.push("Spam or Malicious Search Engine Optimization (“SEO”):");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 39, filename: "views/home/tos.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 39, filename: jade_debug[0].filename });
buf.push(" If you engage in behavior that is inconsistent with ordinary use of the Service, as described in the TOS, including, but not limited to, posting Content that contains malicious SEO optimizations; using bots to spam accounts and/or obtain private information from ScribDen users; or creating an account for strictly commercial purposes, we reserve the right to flag, restrict, or terminate your Account at any time without notice.");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 40, filename: "views/home/tos.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 41, filename: "views/home/tos.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 41, filename: jade_debug[0].filename });
buf.push("Offensive content:");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 42, filename: "views/home/tos.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 42, filename: jade_debug[0].filename });
buf.push(" ScribDen is a social media platform that falls under the DMCA Safe Harbor Agreement and, as such, cannot be held responsible for any user-generated Content that appears on its Service. Without imposing legal accountability where none exists, ScribDen reserves the right, at its sole discretion, to suspend any Account, remove any Content, and/or restrict access to any part of the Service that contains full nudity, violence, obscenity, gang-related Content, hate-based Content based on racial, ethnic, gender, transgender, disability, or sexual orientation, harassment of other users, endangerment to minors, incitation to violence or criminal activity, violation of another person’s intellectual property rights, or Content that is otherwise offensive or inappropriate under the TOS, in order to maintain a safe environment for all of its users.");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 43, filename: "views/home/tos.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 44, filename: "views/home/tos.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 44, filename: jade_debug[0].filename });
buf.push("U.S. Court orders and Police investigations:");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 45, filename: "views/home/tos.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 45, filename: jade_debug[0].filename });
buf.push(" ScribDen shall not be held responsible for retaining any user Content or information that has been deleted or purged during the ordinary course of business.");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift({ lineno: 46, filename: "views/home/tos.jade" });
buf.push("<section class=\"sd-u-align--left\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 47, filename: "views/home/tos.jade" });
buf.push("<h3 class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 47, filename: jade_debug[0].filename });
buf.push("X. Content");
jade_debug.shift();
jade_debug.shift();
buf.push("</h3>");
jade_debug.shift();
jade_debug.unshift({ lineno: 48, filename: "views/home/tos.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 48, filename: jade_debug[0].filename });
buf.push("ScribDen falls under the DMCA Safe Harbor Agreement and cannot control, or be held responsible or liable, for any of the Content that appears on the Service. Without limiting the generality of the foregoing, ScribDen imposes certain guidelines to promote the safety and security of all of its users. By using the Service, you hereby agree to comply with the following guidelines for posting Content on the Service. Failure to comply with the guidelines set forth below may result in flagging or restricting access to any and all Content posted to the Service, deletion of said Content, and/or suspension of your Account without further notice:");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 49, filename: "views/home/tos.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 50, filename: "views/home/tos.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 50, filename: jade_debug[0].filename });
buf.push("Offensive and Inappropriate Content:");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 51, filename: "views/home/tos.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 51, filename: jade_debug[0].filename });
buf.push("Should any Content that you have posted be reported to ScribDen as being offensive or inappropriate, ScribDen has the right to flag, restrict access, or delete said Content at any time without prior notice. In addition, ScribDen might call upon you to retract or modify the Content in question within a reasonable amount of time, as determined by the ScribDen staff. Should you fail to meet such a request, ScribDen may flag, restrict access, delete said Content, or terminate your Account at its sole discretion without assuming control, responsibility, or liability for the Content posted on the Service under the terms of the DMCA Safe Harbor Agreement. Should Content be reported to ScribDen as containing full nudity, violence, obscenity, gang-related Content, hate-based Content based on racial, ethnic, gender, transgender, disability, or sexual orientation, harassment of other users, endangerment to minors, incitation to violence or criminal activity, violation of another person’s intellectual property rights, or Content that is otherwise offensive or inappropriate under the TOS, ScribDen reserves the right to flag, restrict access, and/or delete said Content and/or suspend your Account at any time without notice;");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 52, filename: "views/home/tos.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 53, filename: "views/home/tos.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 53, filename: jade_debug[0].filename });
buf.push("No Control or Liability for User-Generated Content on the Service:");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 54, filename: "views/home/tos.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 54, filename: jade_debug[0].filename });
buf.push("ScribDen claims no ownership or control over any Content posted by its users. The author retains all patent, trademarks, and copyrights to all posted Content, and is fully responsible for protecting said rights. While ScribDen will comply with all lawful DMCA claims and remove copyright- and/or trademark-protected Content in a timely manner, it is not responsible for policing said rights for its users. By posting Content to ScribDen, you hereby acknowledge and agree that you have all rights necessary to post such Content (and for ScribDen to serve such Content) without violation of any laws or regulations, and/or intellectual property or other rights of third parties;");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 55, filename: "views/home/tos.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 56, filename: "views/home/tos.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 56, filename: jade_debug[0].filename });
buf.push("Content Delivery and Subscription Fees:");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 57, filename: "views/home/tos.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 57, filename: jade_debug[0].filename });
buf.push("ScribDen reserves the right, without limitation except by law, to serve any user Content on the web, through downloadable clients, mobile platforms, and otherwise;");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 58, filename: "views/home/tos.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 59, filename: "views/home/tos.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 59, filename: jade_debug[0].filename });
buf.push("No Liability for Content Accuracy, Reliability, or Legality:");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 60, filename: "views/home/tos.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 60, filename: jade_debug[0].filename });
buf.push("You hereby acknowledge that ScribDen does not pre-screen Content, but that ScribDen shall have the right (but not the obligation), at its sole discretion, to remove or refuse to remove any Content found on the Service at any time without prior notice. Without limiting the foregoing, ScribDen shall have the right, but not the obligation, to remove any Content that violates the TOS or is otherwise objectionable, or that infringes or is alleged to infringe upon, intellectual property rights. You agree that you must evaluate, and bear all risks associated with, the use of any Content that appears on the Service, including any reliance on the accuracy, completeness, or usefulness of such Content. Furthermore, ScribDen reserves the right to limit access to your Account if you are found to be in violation of the TOS, including without limitation the User Conduct described below, by flagging, restricting access or deleting Content, suspending or deleting your Account, and/or removing your information from the user directory, search engine, and all other methods used to identify ScribDen users at any time without prior notice;");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift({ lineno: 61, filename: "views/home/tos.jade" });
buf.push("<section class=\"sd-u-align--left\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 62, filename: "views/home/tos.jade" });
buf.push("<h3 class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 62, filename: jade_debug[0].filename });
buf.push("XI. SCRIBDEN.COM PROPRIETARY RIGHTS");
jade_debug.shift();
jade_debug.shift();
buf.push("</h3>");
jade_debug.shift();
jade_debug.unshift({ lineno: 63, filename: "views/home/tos.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 63, filename: jade_debug[0].filename });
buf.push("You acknowledge and agree that the Service, and any necessary software used in connection with the Service (referred to as \"Software\"), may contain proprietary and confidential information that is protected by applicable laws governing intellectual property, proprietary rights and the like. All ScribDen code and specifications, and all other code and specifications for the Software and the operation of the Service, are subject to their express or implied licenses. You further acknowledge and agree that Content contained in information presented to you through the Service is protected by copyrights, trademarks, service marks, patents or other proprietary rights and laws. Except as expressly authorized by ScribDen, you agree not to modify, rent, lease, sell, distribute, or create derivative works based on the Content, the Service or the Software, in whole or in part.￼");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift({ lineno: 64, filename: "views/home/tos.jade" });
buf.push("<section class=\"sd-u-align--left\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 65, filename: "views/home/tos.jade" });
buf.push("<h3 class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 65, filename: jade_debug[0].filename });
buf.push("XII. USER CONDUCT");
jade_debug.shift();
jade_debug.shift();
buf.push("</h3>");
jade_debug.shift();
jade_debug.unshift({ lineno: 66, filename: "views/home/tos.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 66, filename: jade_debug[0].filename });
buf.push("You understand that all Content, including without limitation, all information, data, text, software, music, sound, photographs, graphics, video, messages, or other materials, whether publicly posted or privately transmitted, are the sole responsibility of the user who posted the Content. ScribDen does not control Content posted via the Service and, as such, does not guarantee the validity of such Content. You also understand that by using the Service, you may be exposed to Content that is offensive, indecent, or objectionable. Should Content be found or reported to be in violation with, but not limited to, the following terms, ScribDen may, at its sole discretion, flag, restrict access, delete, terminate the Account, or take any other actions that it deems necessary to enforce the spirit of the TOS.");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 67, filename: "views/home/tos.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 67, filename: jade_debug[0].filename });
buf.push("You agree to NOT use the Service to:");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 68, filename: "views/home/tos.jade" });
buf.push("<ul class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 69, filename: "views/home/tos.jade" });
buf.push("<li>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 69, filename: jade_debug[0].filename });
buf.push("Upload, post or otherwise transmit any Content that is unlawful, harmful, threatening, abusive, harassing, tortuous, defamatory, vulgar, obscene, libelous, invasive to another's privacy (including, but not limited to, posting the address, email, phone number, or any other contact information without the written consent of the owner of such information), or Content containing full nudity, violence, obscenity, gang-related Content, hate-based Content based on racial, ethnic, gender, transgender, disability, or sexual orientation, harassment of other users, endangerment to minors, incitation to violence or criminal activity, violation of another person’s intellectual property rights, or Content that is otherwise offensive or inappropriate under the TOS;");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 70, filename: "views/home/tos.jade" });
buf.push("<li>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 70, filename: jade_debug[0].filename });
buf.push("Impersonate any person or entity, including, but not limited to, a ScribDen staff member or volunteer, or falsely state or otherwise misrepresent your affiliation with ScribDen or any other person or entity;");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 71, filename: "views/home/tos.jade" });
buf.push("<li>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 71, filename: jade_debug[0].filename });
buf.push("Forge headers or otherwise manipulate identifiers in order to disguise the origin of any Content transmitted through the Service;");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 72, filename: "views/home/tos.jade" });
buf.push("<li>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 72, filename: jade_debug[0].filename });
buf.push("Upload, post, or otherwise transmit any Content that you do not have a right to transmit under any law or under contractual or fiduciary relationships (such as inside information, proprietary, and confidential information learned or disclosed as part of employment relationships or under nondisclosure agreements);");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 73, filename: "views/home/tos.jade" });
buf.push("<li>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 73, filename: jade_debug[0].filename });
buf.push("Upload, post, or otherwise transmit any Content that infringes any patent, trademark, trade secret, copyright, or other proprietary right of a third party without express consent;");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 74, filename: "views/home/tos.jade" });
buf.push("<li>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 74, filename: jade_debug[0].filename });
buf.push("Upload, post or otherwise transmit any unsolicited or unauthorized advertising, promotional materials, \"junk mail,\" \"spam,\" \"chain letters,\" \"pyramid schemes,\" or any other form of solicitation;");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 75, filename: "views/home/tos.jade" });
buf.push("<li>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 75, filename: jade_debug[0].filename });
buf.push("Upload, post, or otherwise transmit any material that contains software viruses or any other computer code, files, or programs designed to interrupt, destroy, or limit the functionality of any computer software or hardware or telecommunications equipment;");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 76, filename: "views/home/tos.jade" });
buf.push("<li>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 76, filename: jade_debug[0].filename });
buf.push("Interfere with or disrupt the Service or servers or networks connected to the Service, or disobey any requirements, procedures, policies, or regulations of networks connected to the Service;");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 77, filename: "views/home/tos.jade" });
buf.push("<li>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 77, filename: jade_debug[0].filename });
buf.push("Intentionally or unintentionally violate any applicable local, state, national, or international law, including, but not limited to, regulations promulgated by the U.S. Securities and Exchange Commission, any rules of any national or other securities exchange, including, without limitation, the New York Stock Exchange, the American Stock Exchange, or the NASDAQ, and any regulations having the force of law;");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 78, filename: "views/home/tos.jade" });
buf.push("<li>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 78, filename: jade_debug[0].filename });
buf.push("\"Stalk\" or otherwise harass another person or company;");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 79, filename: "views/home/tos.jade" });
buf.push("<li>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 79, filename: jade_debug[0].filename });
buf.push("Collect or store personal data about other users;");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 80, filename: "views/home/tos.jade" });
buf.push("<li>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 80, filename: jade_debug[0].filename });
buf.push("Promote or provide instructional information about illegal activities, promote physical harm or injury against any governmental entity, group or individual, or promote any act of cruelty to animals. This may include, but is not limited to, providing instructions on how to assemble bombs, grenades, and other weapons or incendiary devices;");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 81, filename: "views/home/tos.jade" });
buf.push("<li>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 81, filename: jade_debug[0].filename });
buf.push("Use the ScribDen Service solely to promote and/or drive traffic to another website, business, or commercial enterprise;");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 82, filename: "views/home/tos.jade" });
buf.push("<li>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 82, filename: jade_debug[0].filename });
buf.push("Allow other users to access and/or use your Account in a manner that violates ScribDen's TOS;");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 83, filename: "views/home/tos.jade" });
buf.push("<li>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 83, filename: jade_debug[0].filename });
buf.push("Engage in commercial activities on behalf of ScribDen without prior approval;");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 84, filename: "views/home/tos.jade" });
buf.push("<li>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 84, filename: jade_debug[0].filename });
buf.push("Solicit passwords or personal identifying information for unintended, commercial or unlawful purposes from other users.");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 85, filename: "views/home/tos.jade" });
buf.push("<li>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 85, filename: jade_debug[0].filename });
buf.push("Exceed the intended scope of the Service, for example, accessing and using features that you do not have a right to use, or deleting, adding to, or otherwise changing other people's entries or other Content without express permission.");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 86, filename: "views/home/tos.jade" });
buf.push("<li>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 86, filename: jade_debug[0].filename });
buf.push("Make excessive or harmful automated use of the system, such as implementing malicious SEO tags, spamming, and/or utilizing bots or other malware to gain access to user Accounts and/or information.");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.shift();
buf.push("</ul>");
jade_debug.shift();
jade_debug.unshift({ lineno: 87, filename: "views/home/tos.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 87, filename: jade_debug[0].filename });
buf.push("If ScribDen determines, in its sole discretion, that any user has violated the TOS, ScribDen reserves the right to terminate such user's Account at any time without prior notice. ");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift({ lineno: 88, filename: "views/home/tos.jade" });
buf.push("<section class=\"sd-u-align--left\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 89, filename: "views/home/tos.jade" });
buf.push("<h3 class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 89, filename: jade_debug[0].filename });
buf.push("XIII. DISCLAIMER OF WARRANTIES");
jade_debug.shift();
jade_debug.shift();
buf.push("</h3>");
jade_debug.shift();
jade_debug.unshift({ lineno: 90, filename: "views/home/tos.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 90, filename: jade_debug[0].filename });
buf.push("YOU EXPRESSLY UNDERSTAND AND AGREE THAT:");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 91, filename: "views/home/tos.jade" });
buf.push("<ul class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 92, filename: "views/home/tos.jade" });
buf.push("<li>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 92, filename: jade_debug[0].filename });
buf.push("(a) YOUR USE OF THE SERVICE IS AT YOUR SOLE RISK. THE SERVICE IS PROVIDED ON AN \"AS IS\" AND \"AS AVAILABLE\" BASIS. SCRIBDEN EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 93, filename: "views/home/tos.jade" });
buf.push("<li>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 93, filename: jade_debug[0].filename });
buf.push("(b) SCRIBDEN MAKES NO WARRANTY THAT (i) THE SERVICE WILL MEET YOUR REQUIREMENTS, (ii) THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (iii) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICE WILL BE ACCURATE OR RELIABLE, (iv) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICE WILL MEET YOUR EXPECTATIONS, AND (V) ANY ERRORS IN THE SOFTWARE WILL BE CORRECTED.");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 94, filename: "views/home/tos.jade" });
buf.push("<li>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 94, filename: jade_debug[0].filename });
buf.push("(c) ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICE IS DONE AT YOUR OWN DISCRETION AND RISK, AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA OR OTHER LIABILITY THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL.");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 95, filename: "views/home/tos.jade" });
buf.push("<li>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 95, filename: jade_debug[0].filename });
buf.push("(d) NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM SCRIBDEN.COM OR THROUGH OR FROM THE SERVICE SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THE TOS.");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.shift();
buf.push("</ul>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift({ lineno: 96, filename: "views/home/tos.jade" });
buf.push("<section class=\"sd-u-align--left\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 97, filename: "views/home/tos.jade" });
buf.push("<h3 class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 97, filename: jade_debug[0].filename });
buf.push("XIV. LIMITATION OF LIABILITY");
jade_debug.shift();
jade_debug.shift();
buf.push("</h3>");
jade_debug.shift();
jade_debug.unshift({ lineno: 98, filename: "views/home/tos.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 98, filename: jade_debug[0].filename });
buf.push("YOU EXPRESSLY UNDERSTAND AND AGREE THAT SCRIBDEN SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF SCRIBDEN HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM: (i) THE USE OR THE INABILITY TO USE THE SERVICE; (ii) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO THROUGH OR FROM THE SERVICE; (iii) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (iv) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE SERVICE; OR (v) ANY OTHER MATTER RELATING TO THE SERVICE.");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift({ lineno: 99, filename: "views/home/tos.jade" });
buf.push("<section class=\"sd-u-align--left\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 100, filename: "views/home/tos.jade" });
buf.push("<h3 class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 100, filename: jade_debug[0].filename });
buf.push("XV. U.S. GOVERNMENT RESTRICTED RIGHTS");
jade_debug.shift();
jade_debug.shift();
buf.push("</h3>");
jade_debug.shift();
jade_debug.unshift({ lineno: 101, filename: "views/home/tos.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 101, filename: jade_debug[0].filename });
buf.push("The materials on ScribDen are provided with \"RESTRICTED RIGHTS.\" Use, duplication, or disclosure by the U.S. Government is subject to restrictions as set forth in applicable laws and regulations. Use of the materials by the U.S. Government constitutes acknowledgment of ScribDen’s proprietary rights in them.");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift({ lineno: 102, filename: "views/home/tos.jade" });
buf.push("<section class=\"sd-u-align--left\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 103, filename: "views/home/tos.jade" });
buf.push("<h3 class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 103, filename: jade_debug[0].filename });
buf.push("XVI. GENERAL INFORMATION");
jade_debug.shift();
jade_debug.shift();
buf.push("</h3>");
jade_debug.shift();
jade_debug.unshift({ lineno: 104, filename: "views/home/tos.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 104, filename: jade_debug[0].filename });
buf.push("The TOS constitutes the entire agreement between you and ScribDen and governs your use of the Service, superseding any prior agreements between you and ScribDen (including, but not limited to, any prior versions of the TOS) and any prior representations by ScribDen. The laws of the State of Texas, U.S.A, shall govern the TOS and the relationship between you and ScribDen, without regard to its conflict of law provisions. You and ScribDen agree to submit to the personal and exclusive jurisdiction of the courts located within the county of Austin, Texas, U.S.A. The failure of ScribDen to exercise or enforce any right or provision of the TOS shall not constitute a waiver of such right or provision. If any provision of the TOS is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties' intentions as reflected in the provision, and the other provisions of the TOS remain in full force and effect. You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of, or related to, use of the Service or the TOS must be filed within one (1) year after such claim or cause of action arose or be forever barred. The section titles in the TOS are for convenience only and have no legal or contractual effect.");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift({ lineno: 105, filename: "views/home/tos.jade" });
buf.push("<section class=\"sd-u-align--left\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 106, filename: "views/home/tos.jade" });
buf.push("<h3 class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 106, filename: jade_debug[0].filename });
buf.push("XVII. VIOLATIONS");
jade_debug.shift();
jade_debug.shift();
buf.push("</h3>");
jade_debug.shift();
jade_debug.unshift({ lineno: 107, filename: "views/home/tos.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 107, filename: jade_debug[0].filename });
buf.push("Please send an email to admin@scribden.com for any violations.");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift({ lineno: 108, filename: "views/home/tos.jade" });
buf.push("<section class=\"sd-u-align--left\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 109, filename: "views/home/tos.jade" });
buf.push("<h3 class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 109, filename: jade_debug[0].filename });
buf.push("XVIII. REVISIONS");
jade_debug.shift();
jade_debug.shift();
buf.push("</h3>");
jade_debug.shift();
jade_debug.unshift({ lineno: 110, filename: "views/home/tos.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 110, filename: jade_debug[0].filename });
buf.push("ScribDen may revise the TOS found at this URL, in whole or in part, without notice. By using this Site, you hereby acknowledge and agree to be bound by any such revisions and should therefore periodically visit this page to determine the current Terms of Service to which you are bound.");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.shift();
buf.push("</article>");
jade_debug.shift();
jade_debug.shift();
buf.push("</main>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();}.call(this,"require" in locals_for_with?locals_for_with.require:typeof require!=="undefined"?require:undefined,"undefined" in locals_for_with?locals_for_with.undefined:typeof undefined!=="undefined"?undefined:undefined));;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade_debug[0].filename, jade_debug[0].lineno, "//- each action can have its own partial view, and use a model to alter the rendered HTML\n//- http://taunus.bevacqua.io/getting-started#using-jade-as-your-view-engine\ndiv.sd-u-align--center\n  include ../partials/flash\n  include ../partials/home_header\n  main.sd-o-main.sd-o-frame-content\n    article\n      h2.sd-t-wire Terms of Service\n      section.sd-u-align--left\n        h3.sd-t-wire I. ACCEPTANCE OF TERMS\n        p.sd-t-wire Hexelberry Studios, ScribDen.com, (\"ScribDen\" or \"Service\") provides the following service to you (\"You\" or \"User\"), subject to these Terms of Service (\"TOS\"), which may be updated periodically without prior notice. BY COMPLETING THE REGISTRATION PROCESS AND/OR USING THE SERVICE YOU HEREBY AGREE THAT YOU ARE ELIGIBLE FOR A SCRIBDEN ACCOUNT AND ARE BOUND BY THESE TERMS AND CONDITIONS, AS DESCRIBED BELOW. Your use of the Service implies your consent to the TOS. It is your responsibility to check if there have been changes to the TOS. Failure to comply with these TOS may result in account suspension, or account deletion at any time, without prior notice.\n      section.sd-u-align--left\n        h3.sd-t-wire II. YOUR REGISTRATION OBLIGATIONS\n        p.sd-t-wire Account registration is required in order to create a ScribDen account. During registration, all users are required to provide accurate, complete, and current information about themselves in all required fields. Should any of your own information change after submitting it to ScribDen, you are required to update that information as soon as possible. Should ScribDen suspect that your personal information is not complete, current, or accurate, your Account may be suspended or terminated without further notice. ScribDen is committed to being a safe and secure environment for all its users. You must be at least 13 years of age to use the Service. Users who are found to be under 13 years of age may be suspended from the Service without notice.\n      section.sd-u-align--left\n        h3.sd-t-wire III. SCRIBDEN.COM PRIVACY POLICY\n        p.sd-t-wire Your use of the Service is subject to ScribDen’s privacy policy. For information on ScribDen’s privacy practices, please see the entire privacy policy at \n          a.sd-t-wire(href='/privacy') http://www.scribden.com/privacy.\n      section.sd-u-align--left\n        h3.sd-t-wire IV. INDEMNITY\n        p.sd-t-wire You agree to indemnify and hold ScribDen, and its subsidiaries, affiliates, officers, agents, co-branders or other partners, and employees, harmless from any alleged claim or demand, including reasonable attorney fees, made by any third party due to or arising out of your Content, your use of the Service, your connection to the Service, your violation of the TOS, or your violation of any rights of others, whether you are a registered user or not. The user is solely responsible for their actions when using the Service, including, but not limited to, costs incurred for Internet access.\n      section.sd-u-align--left\n        h3.sd-t-wire V. SPECIAL ADMONITIONS FOR INTERNATIONAL USE\n        p.sd-t-wire Recognizing the global nature of the Internet, you agree to comply with all local laws regarding online conduct and acceptable Content. Specifically, you agree to comply with all applicable laws regarding the transmission of technical data exported from the United States and the country in which you reside.\n      section.sd-u-align--left\n        h3.sd-t-wire VI. GENERAL PRACTICES REGARDING USE AND STORAGE\n        p.sd-t-wire You acknowledge that ScribDen may be required to send you emails regarding your use of the Service. ScribDen will never ask you to submit personal information or verify your Account information in the form of an email. Should you receive any such communications, please do not respond, and forward it to admin@scribden.com at once.\n      section.sd-u-align--left\n        h3.sd-t-wire VII. MODIFICATIONS TO SERVICE\n        p.sd-t-wire ScribDen reserves the right to modify or discontinue, temporarily or permanently, the Service (or any part thereof) with or without notice at any time. You agree that ScribDen shall not be held liable to you or to any third party for any modification, suspension, or discontinuance of the Service.\n      section.sd-u-align--left\n        h3.sd-t-wire VIII. NO RESALE OF SERVICE\n        p.sd-t-wire You agree not to reproduce, duplicate, copy, sell, resell, or exploit any portion of the Service, use of the Service, or access to the Service.\n      section.sd-u-align--left\n        h3.sd-t-wire IX. TERMINATION\n        p.sd-t-wire By using the ScribDen service, you hereby acknowledge and agree that ScribDen may, at its sole discretion, block, restrict, or terminate access; suspend or delete any Account; and flag or remove any Content found within the Service, for any reason, at any time, without prior notice.\n        p.sd-t-wire\n          strong Spam or Malicious Search Engine Optimization (“SEO”):\n          span  If you engage in behavior that is inconsistent with ordinary use of the Service, as described in the TOS, including, but not limited to, posting Content that contains malicious SEO optimizations; using bots to spam accounts and/or obtain private information from ScribDen users; or creating an account for strictly commercial purposes, we reserve the right to flag, restrict, or terminate your Account at any time without notice.\n        p.sd-t-wire\n          strong Offensive content:\n          span  ScribDen is a social media platform that falls under the DMCA Safe Harbor Agreement and, as such, cannot be held responsible for any user-generated Content that appears on its Service. Without imposing legal accountability where none exists, ScribDen reserves the right, at its sole discretion, to suspend any Account, remove any Content, and/or restrict access to any part of the Service that contains full nudity, violence, obscenity, gang-related Content, hate-based Content based on racial, ethnic, gender, transgender, disability, or sexual orientation, harassment of other users, endangerment to minors, incitation to violence or criminal activity, violation of another person’s intellectual property rights, or Content that is otherwise offensive or inappropriate under the TOS, in order to maintain a safe environment for all of its users.\n        p.sd-t-wire\n          strong U.S. Court orders and Police investigations:\n          span  ScribDen shall not be held responsible for retaining any user Content or information that has been deleted or purged during the ordinary course of business.\n      section.sd-u-align--left\n        h3.sd-t-wire X. Content\n        p.sd-t-wire ScribDen falls under the DMCA Safe Harbor Agreement and cannot control, or be held responsible or liable, for any of the Content that appears on the Service. Without limiting the generality of the foregoing, ScribDen imposes certain guidelines to promote the safety and security of all of its users. By using the Service, you hereby agree to comply with the following guidelines for posting Content on the Service. Failure to comply with the guidelines set forth below may result in flagging or restricting access to any and all Content posted to the Service, deletion of said Content, and/or suspension of your Account without further notice:\n        p.sd-t-wire\n          strong Offensive and Inappropriate Content:\n          span Should any Content that you have posted be reported to ScribDen as being offensive or inappropriate, ScribDen has the right to flag, restrict access, or delete said Content at any time without prior notice. In addition, ScribDen might call upon you to retract or modify the Content in question within a reasonable amount of time, as determined by the ScribDen staff. Should you fail to meet such a request, ScribDen may flag, restrict access, delete said Content, or terminate your Account at its sole discretion without assuming control, responsibility, or liability for the Content posted on the Service under the terms of the DMCA Safe Harbor Agreement. Should Content be reported to ScribDen as containing full nudity, violence, obscenity, gang-related Content, hate-based Content based on racial, ethnic, gender, transgender, disability, or sexual orientation, harassment of other users, endangerment to minors, incitation to violence or criminal activity, violation of another person’s intellectual property rights, or Content that is otherwise offensive or inappropriate under the TOS, ScribDen reserves the right to flag, restrict access, and/or delete said Content and/or suspend your Account at any time without notice;\n        p.sd-t-wire\n          strong No Control or Liability for User-Generated Content on the Service:\n          span ScribDen claims no ownership or control over any Content posted by its users. The author retains all patent, trademarks, and copyrights to all posted Content, and is fully responsible for protecting said rights. While ScribDen will comply with all lawful DMCA claims and remove copyright- and/or trademark-protected Content in a timely manner, it is not responsible for policing said rights for its users. By posting Content to ScribDen, you hereby acknowledge and agree that you have all rights necessary to post such Content (and for ScribDen to serve such Content) without violation of any laws or regulations, and/or intellectual property or other rights of third parties;\n        p.sd-t-wire\n          strong Content Delivery and Subscription Fees:\n          span ScribDen reserves the right, without limitation except by law, to serve any user Content on the web, through downloadable clients, mobile platforms, and otherwise;\n        p.sd-t-wire\n          strong No Liability for Content Accuracy, Reliability, or Legality:\n          span You hereby acknowledge that ScribDen does not pre-screen Content, but that ScribDen shall have the right (but not the obligation), at its sole discretion, to remove or refuse to remove any Content found on the Service at any time without prior notice. Without limiting the foregoing, ScribDen shall have the right, but not the obligation, to remove any Content that violates the TOS or is otherwise objectionable, or that infringes or is alleged to infringe upon, intellectual property rights. You agree that you must evaluate, and bear all risks associated with, the use of any Content that appears on the Service, including any reliance on the accuracy, completeness, or usefulness of such Content. Furthermore, ScribDen reserves the right to limit access to your Account if you are found to be in violation of the TOS, including without limitation the User Conduct described below, by flagging, restricting access or deleting Content, suspending or deleting your Account, and/or removing your information from the user directory, search engine, and all other methods used to identify ScribDen users at any time without prior notice;\n      section.sd-u-align--left\n        h3.sd-t-wire XI. SCRIBDEN.COM PROPRIETARY RIGHTS\n        p.sd-t-wire You acknowledge and agree that the Service, and any necessary software used in connection with the Service (referred to as \"Software\"), may contain proprietary and confidential information that is protected by applicable laws governing intellectual property, proprietary rights and the like. All ScribDen code and specifications, and all other code and specifications for the Software and the operation of the Service, are subject to their express or implied licenses. You further acknowledge and agree that Content contained in information presented to you through the Service is protected by copyrights, trademarks, service marks, patents or other proprietary rights and laws. Except as expressly authorized by ScribDen, you agree not to modify, rent, lease, sell, distribute, or create derivative works based on the Content, the Service or the Software, in whole or in part.￼\n      section.sd-u-align--left\n        h3.sd-t-wire XII. USER CONDUCT\n        p.sd-t-wire You understand that all Content, including without limitation, all information, data, text, software, music, sound, photographs, graphics, video, messages, or other materials, whether publicly posted or privately transmitted, are the sole responsibility of the user who posted the Content. ScribDen does not control Content posted via the Service and, as such, does not guarantee the validity of such Content. You also understand that by using the Service, you may be exposed to Content that is offensive, indecent, or objectionable. Should Content be found or reported to be in violation with, but not limited to, the following terms, ScribDen may, at its sole discretion, flag, restrict access, delete, terminate the Account, or take any other actions that it deems necessary to enforce the spirit of the TOS.\n        p.sd-t-wire You agree to NOT use the Service to:\n        ul.sd-t-wire\n          li Upload, post or otherwise transmit any Content that is unlawful, harmful, threatening, abusive, harassing, tortuous, defamatory, vulgar, obscene, libelous, invasive to another's privacy (including, but not limited to, posting the address, email, phone number, or any other contact information without the written consent of the owner of such information), or Content containing full nudity, violence, obscenity, gang-related Content, hate-based Content based on racial, ethnic, gender, transgender, disability, or sexual orientation, harassment of other users, endangerment to minors, incitation to violence or criminal activity, violation of another person’s intellectual property rights, or Content that is otherwise offensive or inappropriate under the TOS;\n          li Impersonate any person or entity, including, but not limited to, a ScribDen staff member or volunteer, or falsely state or otherwise misrepresent your affiliation with ScribDen or any other person or entity;\n          li Forge headers or otherwise manipulate identifiers in order to disguise the origin of any Content transmitted through the Service;\n          li Upload, post, or otherwise transmit any Content that you do not have a right to transmit under any law or under contractual or fiduciary relationships (such as inside information, proprietary, and confidential information learned or disclosed as part of employment relationships or under nondisclosure agreements);\n          li Upload, post, or otherwise transmit any Content that infringes any patent, trademark, trade secret, copyright, or other proprietary right of a third party without express consent;\n          li Upload, post or otherwise transmit any unsolicited or unauthorized advertising, promotional materials, \"junk mail,\" \"spam,\" \"chain letters,\" \"pyramid schemes,\" or any other form of solicitation;\n          li Upload, post, or otherwise transmit any material that contains software viruses or any other computer code, files, or programs designed to interrupt, destroy, or limit the functionality of any computer software or hardware or telecommunications equipment;\n          li Interfere with or disrupt the Service or servers or networks connected to the Service, or disobey any requirements, procedures, policies, or regulations of networks connected to the Service;\n          li Intentionally or unintentionally violate any applicable local, state, national, or international law, including, but not limited to, regulations promulgated by the U.S. Securities and Exchange Commission, any rules of any national or other securities exchange, including, without limitation, the New York Stock Exchange, the American Stock Exchange, or the NASDAQ, and any regulations having the force of law;\n          li \"Stalk\" or otherwise harass another person or company;\n          li Collect or store personal data about other users;\n          li Promote or provide instructional information about illegal activities, promote physical harm or injury against any governmental entity, group or individual, or promote any act of cruelty to animals. This may include, but is not limited to, providing instructions on how to assemble bombs, grenades, and other weapons or incendiary devices;\n          li Use the ScribDen Service solely to promote and/or drive traffic to another website, business, or commercial enterprise;\n          li Allow other users to access and/or use your Account in a manner that violates ScribDen's TOS;\n          li Engage in commercial activities on behalf of ScribDen without prior approval;\n          li Solicit passwords or personal identifying information for unintended, commercial or unlawful purposes from other users.\n          li Exceed the intended scope of the Service, for example, accessing and using features that you do not have a right to use, or deleting, adding to, or otherwise changing other people's entries or other Content without express permission.\n          li Make excessive or harmful automated use of the system, such as implementing malicious SEO tags, spamming, and/or utilizing bots or other malware to gain access to user Accounts and/or information.\n        p.sd-t-wire If ScribDen determines, in its sole discretion, that any user has violated the TOS, ScribDen reserves the right to terminate such user's Account at any time without prior notice. \n      section.sd-u-align--left\n        h3.sd-t-wire XIII. DISCLAIMER OF WARRANTIES\n        p.sd-t-wire YOU EXPRESSLY UNDERSTAND AND AGREE THAT:\n        ul.sd-t-wire\n          li (a) YOUR USE OF THE SERVICE IS AT YOUR SOLE RISK. THE SERVICE IS PROVIDED ON AN \"AS IS\" AND \"AS AVAILABLE\" BASIS. SCRIBDEN EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.\n          li (b) SCRIBDEN MAKES NO WARRANTY THAT (i) THE SERVICE WILL MEET YOUR REQUIREMENTS, (ii) THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (iii) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICE WILL BE ACCURATE OR RELIABLE, (iv) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICE WILL MEET YOUR EXPECTATIONS, AND (V) ANY ERRORS IN THE SOFTWARE WILL BE CORRECTED.\n          li (c) ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICE IS DONE AT YOUR OWN DISCRETION AND RISK, AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA OR OTHER LIABILITY THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL.\n          li (d) NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM SCRIBDEN.COM OR THROUGH OR FROM THE SERVICE SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THE TOS.\n      section.sd-u-align--left\n        h3.sd-t-wire XIV. LIMITATION OF LIABILITY\n        p.sd-t-wire YOU EXPRESSLY UNDERSTAND AND AGREE THAT SCRIBDEN SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF SCRIBDEN HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM: (i) THE USE OR THE INABILITY TO USE THE SERVICE; (ii) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO THROUGH OR FROM THE SERVICE; (iii) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (iv) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE SERVICE; OR (v) ANY OTHER MATTER RELATING TO THE SERVICE.\n      section.sd-u-align--left\n        h3.sd-t-wire XV. U.S. GOVERNMENT RESTRICTED RIGHTS\n        p.sd-t-wire The materials on ScribDen are provided with \"RESTRICTED RIGHTS.\" Use, duplication, or disclosure by the U.S. Government is subject to restrictions as set forth in applicable laws and regulations. Use of the materials by the U.S. Government constitutes acknowledgment of ScribDen’s proprietary rights in them.\n      section.sd-u-align--left\n        h3.sd-t-wire XVI. GENERAL INFORMATION\n        p.sd-t-wire The TOS constitutes the entire agreement between you and ScribDen and governs your use of the Service, superseding any prior agreements between you and ScribDen (including, but not limited to, any prior versions of the TOS) and any prior representations by ScribDen. The laws of the State of Texas, U.S.A, shall govern the TOS and the relationship between you and ScribDen, without regard to its conflict of law provisions. You and ScribDen agree to submit to the personal and exclusive jurisdiction of the courts located within the county of Austin, Texas, U.S.A. The failure of ScribDen to exercise or enforce any right or provision of the TOS shall not constitute a waiver of such right or provision. If any provision of the TOS is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties' intentions as reflected in the provision, and the other provisions of the TOS remain in full force and effect. You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of, or related to, use of the Service or the TOS must be filed within one (1) year after such claim or cause of action arose or be forever barred. The section titles in the TOS are for convenience only and have no legal or contractual effect.\n      section.sd-u-align--left\n        h3.sd-t-wire XVII. VIOLATIONS\n        p.sd-t-wire Please send an email to admin@scribden.com for any violations.\n      section.sd-u-align--left\n        h3.sd-t-wire XVIII. REVISIONS\n        p.sd-t-wire ScribDen may revise the TOS found at this URL, in whole or in part, without notice. By using this Site, you hereby acknowledge and agree to be bound by any such revisions and should therefore periodically visit this page to determine the current Terms of Service to which you are bound.\n        ");
}
}