var jade = require("jadum/runtime");
module.exports = function layout(locals) {
var jade_debug = [{ lineno: 1, filename: "views/layout.jade" }];
try {
var buf = [];
var jade_mixins = {};
var jade_interp;
;var locals_for_with = (locals || {});(function (model, partial) {
jade_debug.unshift({ lineno: 0, filename: "views/layout.jade" });
jade_debug.unshift({ lineno: 1, filename: "views/layout.jade" });
buf.push("<!DOCTYPE html>");
jade_debug.shift();
jade_debug.unshift({ lineno: 2, filename: "views/layout.jade" });
buf.push("<html lang=\"en\" itemscope itemtype=\"http://schema.org/Blog\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 3, filename: "views/layout.jade" });
buf.push("<head>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 5, filename: "views/layout.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 6, filename: "views/layout.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 7, filename: "views/layout.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 7, filename: "views/layout.jade" });
buf.push("");
jade_debug.shift();
jade_debug.unshift({ lineno: 9, filename: "views/layout.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 9, filename: "views/layout.jade" });
buf.push("<title>" + (jade.escape(null == (jade_interp = model.title) ? "" : jade_interp)));
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.shift();
buf.push("</title>");
jade_debug.shift();
jade_debug.unshift({ lineno: 10, filename: "views/layout.jade" });
buf.push("<meta charset=\"utf-8\">");
jade_debug.shift();
jade_debug.unshift({ lineno: 11, filename: "views/layout.jade" });
buf.push("<link rel=\"shortcut icon\" href=\"/favicon.ico\">");
jade_debug.shift();
jade_debug.unshift({ lineno: 12, filename: "views/layout.jade" });
buf.push("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">");
jade_debug.shift();
jade_debug.unshift({ lineno: 13, filename: "views/layout.jade" });
buf.push("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
jade_debug.shift();
jade_debug.unshift({ lineno: 14, filename: "views/layout.jade" });
buf.push("<link rel=\"stylesheet\" type=\"text/css\" href=\"/css/all.css\">");
jade_debug.shift();
jade_debug.unshift({ lineno: 15, filename: "views/layout.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 17, filename: "views/layout.jade" });
jade_debug.shift();
jade_debug.shift();
buf.push("</head>");
jade_debug.shift();
jade_debug.unshift({ lineno: 17, filename: "views/layout.jade" });
buf.push("<body data-taunus=\"model\" class=\"sd-t-default\">" + (null == (jade_interp = partial) ? "" : jade_interp));
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.shift();
buf.push("</body>");
jade_debug.shift();
jade_debug.unshift({ lineno: 19, filename: "views/layout.jade" });
buf.push("<script type=\"text/javascript\">");
jade_debug.unshift({ lineno: 19, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 19, filename: jade_debug[0].filename });
buf.push("var wf, ");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 19, filename: jade_debug[0].filename });
buf.push("  s,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 19, filename: jade_debug[0].filename });
buf.push("  i,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 19, filename: jade_debug[0].filename });
buf.push("  numElements,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 19, filename: jade_debug[0].filename });
buf.push("  currentElement,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 19, filename: jade_debug[0].filename });
buf.push("  nojs;");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 19, filename: jade_debug[0].filename });
buf.push("  ");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 19, filename: jade_debug[0].filename });
buf.push("if ('querySelector' in document && 'localStorage' in window && 'addEventListener' in window) {");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 19, filename: jade_debug[0].filename });
buf.push("  // only add javascript if this is a capable browser");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 19, filename: jade_debug[0].filename });
buf.push("  wf = document.createElement('script');");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 19, filename: jade_debug[0].filename });
buf.push("  wf.src = '/js/all.js';");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 19, filename: jade_debug[0].filename });
buf.push("  wf.type = 'text/javascript';");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 19, filename: jade_debug[0].filename });
buf.push("  wf.async = 'true';");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 19, filename: jade_debug[0].filename });
buf.push("  s = document.getElementsByTagName('script')[0];");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 19, filename: jade_debug[0].filename });
buf.push("  s.parentNode.insertBefore(wf, s);");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 19, filename: jade_debug[0].filename });
buf.push("}");
jade_debug.shift();
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.shift();
buf.push("</html>");
jade_debug.shift();
jade_debug.shift();}.call(this,"model" in locals_for_with?locals_for_with.model:typeof model!=="undefined"?model:undefined,"partial" in locals_for_with?locals_for_with.partial:typeof partial!=="undefined"?partial:undefined));;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade_debug[0].filename, jade_debug[0].lineno, "doctype html\nhtml(lang='en', itemscope, itemtype='http://schema.org/Blog')\n  head\n    //- the view layout is useful to set metadata, a title, load scripts and styles\n    //- and also global markup such as a navigation menu or layout structure\n    //- http://taunus.bevacqua.io/getting-started#creating-a-layout\n    \n    //- every controller action should produce a view title\n    title=model.title\n    meta(charset='utf-8')\n    link(rel='shortcut icon', href='/favicon.ico')\n    meta(http-equiv='X-UA-Compatible', content='IE=edge,chrome=1')\n    meta(name='viewport', content='width=device-width, initial-scale=1')\n    link(rel='stylesheet', type='text/css', href='/css/all.css')\n    //-\n     The != syntax below means that whatever is in the value assigned to the element won't be escaped. That's okay because partial is a view where Jade escaped anything that needed escaping, but we wouldn't want HTML tags to be escaped!\n    //- the HTML for the partial view can be placed where needed\n  body.sd-t-default(data-taunus='model')!=partial\n    \n  script(type='text/javascript').\n    var wf, \n      s,\n      i,\n      numElements,\n      currentElement,\n      nojs;\n      \n    if ('querySelector' in document && 'localStorage' in window && 'addEventListener' in window) {\n      // only add javascript if this is a capable browser\n      wf = document.createElement('script');\n      wf.src = '/js/all.js';\n      wf.type = 'text/javascript';\n      wf.async = 'true';\n      s = document.getElementsByTagName('script')[0];\n      s.parentNode.insertBefore(wf, s);\n    }");
}
}