var jade = require("jadum/runtime");
module.exports = function newThread(locals) {
var jade_debug = [{ lineno: 1, filename: "views/app/new_thread.jade" }];
try {
var buf = [];
var jade_mixins = {};
var jade_interp;
;var locals_for_with = (locals || {});(function (require, undefined, user) {
jade_debug.unshift({ lineno: 0, filename: "views/app/new_thread.jade" });
jade_debug.unshift({ lineno: 1, filename: "views/app/new_thread.jade" });
buf.push(require("../partials/generic_header").call(this, locals));
jade_debug.shift();
jade_debug.unshift({ lineno: 2, filename: "views/app/new_thread.jade" });
buf.push("<main class=\"sd-o-main\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: undefined, filename: "views/app/new_thread.jade" });
buf.push(require("../partials/flash").call(this, locals));
jade_debug.shift();
jade_debug.unshift({ lineno: 4, filename: "views/app/new_thread.jade" });
buf.push("<h1 class=\"sd-c-thread__title sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 4, filename: jade_debug[0].filename });
buf.push("New Thread");
jade_debug.shift();
jade_debug.shift();
buf.push("</h1>");
jade_debug.shift();
jade_debug.unshift({ lineno: 5, filename: "views/app/new_thread.jade" });
buf.push("<form name=\"loginForm\" action=\"/api/thread\" method=\"post\" class=\"sd-u-align--center sd-o-frame-content\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 6, filename: "views/app/new_thread.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 7, filename: "views/app/new_thread.jade" });
buf.push("<div>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 8, filename: "views/app/new_thread.jade" });
buf.push("<label for=\"threadDescription\" class=\"sd-c-form__label--medium\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 8, filename: jade_debug[0].filename });
buf.push("description:");
jade_debug.shift();
jade_debug.shift();
buf.push("</label>");
jade_debug.shift();
jade_debug.unshift({ lineno: 9, filename: "views/app/new_thread.jade" });
buf.push("<input id=\"threadDescription\" name=\"description\" type=\"text\" placeholder=\"description\" class=\"sd-t-wire sd-t-wire--field sd-c-form__field--medium\"/>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 10, filename: "views/app/new_thread.jade" });
buf.push("<div>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 11, filename: "views/app/new_thread.jade" });
buf.push("<label for=\"threadRules\" class=\"sd-c-form__label--medium\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 11, filename: jade_debug[0].filename });
buf.push("community ruleset:");
jade_debug.shift();
jade_debug.shift();
buf.push("</label>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 12, filename: "views/app/new_thread.jade" });
buf.push("<fieldset id=\"threadRules\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 13, filename: "views/app/new_thread.jade" });
buf.push("<input type=\"radio\" id=\"standard\" name=\"ruleset\" value=\"standard\" checked=\"checked\" class=\"sd-c-radio-btn\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 14, filename: "views/app/new_thread.jade" });
buf.push("<label for=\"standard\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 14, filename: jade_debug[0].filename });
buf.push("standard");
jade_debug.shift();
jade_debug.shift();
buf.push("</label>");
jade_debug.shift();
jade_debug.unshift({ lineno: 15, filename: "views/app/new_thread.jade" });
buf.push("<p class=\"sd-u-align--left\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 15, filename: jade_debug[0].filename });
buf.push("For most conversations, these rules will suffice. Best used for general casual conversation. The rule of thumb here is just be respectful towards each other.");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 16, filename: "views/app/new_thread.jade" });
buf.push("<input type=\"radio\" id=\"moderate\" name=\"ruleset\" value=\"moderate\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 17, filename: "views/app/new_thread.jade" });
buf.push("<label for=\"moderate\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 17, filename: jade_debug[0].filename });
buf.push("moderate");
jade_debug.shift();
jade_debug.shift();
buf.push("</label>");
jade_debug.shift();
jade_debug.unshift({ lineno: 18, filename: "views/app/new_thread.jade" });
buf.push("<p class=\"sd-u-align--left\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 18, filename: jade_debug[0].filename });
buf.push("This is for general discussion. Make sure you're adding something to the conversation. Stay on topic and be respectful of others' input.");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 20, filename: "views/app/new_thread.jade" });
buf.push("<!--input(type='radio' id='strict' name='ruleset' value='Strict') strict-->");
jade_debug.shift();
jade_debug.unshift({ lineno: 21, filename: "views/app/new_thread.jade" });
buf.push("<!--label(for='strict') These rules are for-->");
jade_debug.shift();
jade_debug.shift();
buf.push("</fieldset>");
jade_debug.shift();
jade_debug.unshift({ lineno: 21, filename: "views/app/new_thread.jade" });
buf.push("<div>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 22, filename: "views/app/new_thread.jade" });
buf.push("<input type=\"hidden\" name=\"createdBy\"" + (jade.attr("value", user.id, true, false)) + "/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 23, filename: "views/app/new_thread.jade" });
buf.push("<button type=\"submit\" class=\"sd-c-btn sd-t-wire sd-t-wire-hover sd-t-wire--field sd-c-btn\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 23, filename: jade_debug[0].filename });
buf.push("Create");
jade_debug.shift();
jade_debug.shift();
buf.push("</button>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</form>");
jade_debug.shift();
jade_debug.shift();
buf.push("</main>");
jade_debug.shift();
jade_debug.shift();}.call(this,"require" in locals_for_with?locals_for_with.require:typeof require!=="undefined"?require:undefined,"undefined" in locals_for_with?locals_for_with.undefined:typeof undefined!=="undefined"?undefined:undefined,"user" in locals_for_with?locals_for_with.user:typeof user!=="undefined"?user:undefined));;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade_debug[0].filename, jade_debug[0].lineno, "include ../partials/generic_header\nmain.sd-o-main\n  include ../partials/flash\n  h1.sd-c-thread__title.sd-t-wire New Thread\n  form.sd-u-align--center.sd-o-frame-content(name='loginForm' action='/api/thread' method='post')\n    //-div\n        label.sd-c-form__label--medium(for='threadName') name:\n        input.sd-t-wire.sd-t-wire--field.sd-c-form__field--medium(id='threadName' name='threadName' type='text' placeholder='name' required)\n    div\n      label.sd-c-form__label--medium(for='threadDescription') description:\n      input.sd-t-wire.sd-t-wire--field.sd-c-form__field--medium(id='threadDescription' name='description' type='text' placeholder='description')\n    div\n      label.sd-c-form__label--medium(for='threadRules') community ruleset:\n    fieldset(id='threadRules')\n      input.sd-c-radio-btn(type='radio' id='standard' name='ruleset' value='standard' checked)\n      label(for='standard') standard\n      p.sd-u-align--left For most conversations, these rules will suffice. Best used for general casual conversation. The rule of thumb here is just be respectful towards each other.\n      input(type='radio' id='moderate' name='ruleset' value='moderate')\n      label(for='moderate') moderate\n      p.sd-u-align--left This is for general discussion. Make sure you're adding something to the conversation. Stay on topic and be respectful of others' input.\n      //input(type='radio' id='strict' name='ruleset' value='Strict') strict\n      //label(for='strict') These rules are for\n    div\n      input(type='hidden' name='createdBy' value=user.id)\n      button.sd-c-btn.sd-t-wire.sd-t-wire-hover.sd-t-wire--field.sd-c-btn(type='submit') Create");
}
}