var jade = require("jadum/runtime");
module.exports = function ruleset(locals) {
var jade_debug = [{ lineno: 1, filename: "views/app/ruleset.jade" }];
try {
var buf = [];
var jade_mixins = {};
var jade_interp;
;var locals_for_with = (locals || {});(function (require, undefined) {
jade_debug.unshift({ lineno: 0, filename: "views/app/ruleset.jade" });
jade_debug.unshift({ lineno: 1, filename: "views/app/ruleset.jade" });
buf.push(require("../partials/generic_header").call(this, locals));
jade_debug.shift();
jade_debug.unshift({ lineno: 2, filename: "views/app/ruleset.jade" });
buf.push("<main class=\"sd-o-main\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: undefined, filename: "views/app/ruleset.jade" });
buf.push(require("../partials/flash").call(this, locals));
jade_debug.shift();
jade_debug.unshift({ lineno: 4, filename: "views/app/ruleset.jade" });
buf.push("<article class=\"sd-o-frame-content\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 5, filename: "views/app/ruleset.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 5, filename: jade_debug[0].filename });
buf.push("Below is a brief explanation of our community rules and expectations for specific topics and situations. If you have any questions about our Community Code of Conduct, please email us at hexelberrystudios@gmail.com.");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 7, filename: "views/app/ruleset.jade" });
buf.push("<section class=\"sd-u-content-padding--top-bottom\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 8, filename: "views/app/ruleset.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 9, filename: "views/app/ruleset.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 9, filename: jade_debug[0].filename });
buf.push("For the");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 10, filename: "views/app/ruleset.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 10, filename: jade_debug[0].filename });
buf.push(" Standard");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 11, filename: "views/app/ruleset.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 11, filename: jade_debug[0].filename });
buf.push(" ruleset, Section I applies.");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 12, filename: "views/app/ruleset.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 13, filename: "views/app/ruleset.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 13, filename: jade_debug[0].filename });
buf.push("For the");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 14, filename: "views/app/ruleset.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 14, filename: jade_debug[0].filename });
buf.push(" Moderate");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 15, filename: "views/app/ruleset.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 15, filename: jade_debug[0].filename });
buf.push(" ruleset, Sections I and II apply.");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 16, filename: "views/app/ruleset.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 17, filename: "views/app/ruleset.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 17, filename: jade_debug[0].filename });
buf.push("For the");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 18, filename: "views/app/ruleset.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 18, filename: jade_debug[0].filename });
buf.push(" Strict");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 19, filename: "views/app/ruleset.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 19, filename: jade_debug[0].filename });
buf.push(" ruleset, Sections I, II, and III apply.");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift({ lineno: 21, filename: "views/app/ruleset.jade" });
buf.push("<section>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 22, filename: "views/app/ruleset.jade" });
buf.push("<h2 class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 22, filename: jade_debug[0].filename });
buf.push("Section I");
jade_debug.shift();
jade_debug.shift();
buf.push("</h2>");
jade_debug.shift();
jade_debug.unshift({ lineno: 24, filename: "views/app/ruleset.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 25, filename: "views/app/ruleset.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 25, filename: jade_debug[0].filename });
buf.push("Abusive Language and Disruptive Behavior:");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 26, filename: "views/app/ruleset.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 26, filename: jade_debug[0].filename });
buf.push(" We do not tolerate abusive or disruptive behavior on ScribDen. This goes for abusive and disruptive comments and behavior that is directed at employees and members alike. Posts that are excessively vulgar, insulting, explicit, or hateful may be removed. Please remember to be respectful and constructive at all times, and help us maintain a friendly and welcoming atmosphere for all.");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 28, filename: "views/app/ruleset.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 29, filename: "views/app/ruleset.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 29, filename: jade_debug[0].filename });
buf.push("Conspiracy Theories and Misinformation:");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 30, filename: "views/app/ruleset.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 30, filename: jade_debug[0].filename });
buf.push(" We do not tolerate the deliberate and malicious spreading of false information. This does not include honest mistakes; rather, this rule pertains to those who go out of their way to spread harmful or malicious rumors about others, including but not limited to members, companies, or public figures.");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 32, filename: "views/app/ruleset.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 33, filename: "views/app/ruleset.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 33, filename: jade_debug[0].filename });
buf.push("No Pirating:");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 34, filename: "views/app/ruleset.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 34, filename: jade_debug[0].filename });
buf.push(" Requesting or sharing material you do not own the copyright to or have permission to share (such as music, software, or art) is not permitted.");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 36, filename: "views/app/ruleset.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 37, filename: "views/app/ruleset.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 37, filename: jade_debug[0].filename });
buf.push("No Stalking:");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 38, filename: "views/app/ruleset.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 38, filename: jade_debug[0].filename });
buf.push(" Persistent harassment of an individual or group of individuals against their wishes is not permitted. If someone asks you to stop, please leave them alone.");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 40, filename: "views/app/ruleset.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 41, filename: "views/app/ruleset.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 41, filename: jade_debug[0].filename });
buf.push("Demands and Threats:");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 42, filename: "views/app/ruleset.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 42, filename: jade_debug[0].filename });
buf.push(" Concerns and requests may be made without needing to resort to demands and threats. We believe they are not constructive. Threats of real-life violence, in particular, are something we take very seriously and do not tolerate.");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 44, filename: "views/app/ruleset.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 45, filename: "views/app/ruleset.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 45, filename: jade_debug[0].filename });
buf.push("Deliberately Disobeying a ScribDen Employee:");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 46, filename: "views/app/ruleset.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 46, filename: jade_debug[0].filename });
buf.push(" Deliberately disobeying a request or action by a  ScribDen employee, is not permitted at any time. As an example, if we close a thread you created and leave an explanation stating why it was closed, you may not re-create the thread.");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 48, filename: "views/app/ruleset.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 49, filename: "views/app/ruleset.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 49, filename: jade_debug[0].filename });
buf.push("Discussing Disciplinary Actions:");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 50, filename: "views/app/ruleset.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 50, filename: jade_debug[0].filename });
buf.push(" If you ever have questions or concerns about a disciplinary action or decision a moderator has made on the forums, or wish to appeal an infraction you’ve received, we ask that you please contact us at hexelberrystudios@gmail.com to do so. Please specify that you are contacting about a forum-related inquiry or appeal. We are happy to discuss and review specific moderation-related actions with you, but we do not allow discussion of any moderation actions or decisions on our forums.");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 52, filename: "views/app/ruleset.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 53, filename: "views/app/ruleset.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 53, filename: jade_debug[0].filename });
buf.push("Flaming:");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 54, filename: "views/app/ruleset.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 54, filename: jade_debug[0].filename });
buf.push(" It’s okay to disagree and debate, but we do ask that you keep all disagreements civil, constructive, and on-topic. If a discussion gets heated and turns into a debate, remember that you should stick to debating the post and/or thread topic. It is never appropriate to resort to personal comments or jabs about those participating in the thread discussion.");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 56, filename: "views/app/ruleset.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 57, filename: "views/app/ruleset.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 57, filename: jade_debug[0].filename });
buf.push("Hate Speech:");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 58, filename: "views/app/ruleset.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 58, filename: jade_debug[0].filename });
buf.push(" We take the use of hate speech very seriously, and have a zero tolerance policy. Our definition of hate speech is prejudice or hateful comments, slurs, or statements that promote violence or intolerance toward others because of the following: Race, Color, National Origin, Gender, Age, Disability, Sexual Orientation, Lifestyle, and any other personally identifying factors.");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 60, filename: "views/app/ruleset.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 61, filename: "views/app/ruleset.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 61, filename: jade_debug[0].filename });
buf.push("Impersonation:");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 62, filename: "views/app/ruleset.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 62, filename: jade_debug[0].filename });
buf.push(" We do not tolerate impersonation of real, living or dead individuals. Impersonation includes using a display name, photos, posts, or any other material with the intent to fool people into believing you are a ScribDen employee, another community member, a celebrity, or anyone else you are not. This does not apply to roleplaying fictional characters, although we prefer that you limit the impersonation of fictional characters to roleplaying threads only.");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 64, filename: "views/app/ruleset.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 65, filename: "views/app/ruleset.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 65, filename: jade_debug[0].filename });
buf.push("Malicious Links:");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 66, filename: "views/app/ruleset.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 66, filename: jade_debug[0].filename });
buf.push(" We do not tolerate the posting of malicious links on our forums, for any reason. This includes but is not limited to links to key-loggers, browser hijackers, or phishing scams.");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 68, filename: "views/app/ruleset.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 69, filename: "views/app/ruleset.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 69, filename: jade_debug[0].filename });
buf.push("Names in Thread Descriptions:");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 70, filename: "views/app/ruleset.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 70, filename: jade_debug[0].filename });
buf.push(" Please refrain from placing the names of ScribDen employees or members in your thread descriptions. Directing a thread at a specific individual, or otherwise using a thread to call someone out, is not considered constructive.");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 72, filename: "views/app/ruleset.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 73, filename: "views/app/ruleset.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 73, filename: jade_debug[0].filename });
buf.push("Personal Information:");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 74, filename: "views/app/ruleset.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 74, filename: jade_debug[0].filename });
buf.push(" For the sake of your own identity protection and personal privacy, we ask that you please do not share any personal information in ScribDen. This also goes for sharing another member’s personal information.");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 76, filename: "views/app/ruleset.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 77, filename: "views/app/ruleset.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 77, filename: jade_debug[0].filename });
buf.push("Thread Bumping:");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 78, filename: "views/app/ruleset.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 78, filename: jade_debug[0].filename });
buf.push(" Please refrain from replying to threads for the sole purpose of “bumping” them. This is considered to be a form of spam because it does not add to the discussion in a constructive or meaningful way. We understand that everyone would like to keep their discussion active and visible, but we encourage you to strive for meaningful and constructive posts instead of posts that consist of nothing more than “bump.”");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 80, filename: "views/app/ruleset.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 81, filename: "views/app/ruleset.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 81, filename: jade_debug[0].filename });
buf.push("Other Cases:");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 82, filename: "views/app/ruleset.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 82, filename: jade_debug[0].filename });
buf.push(" The ScribDen Code of Conduct includes almost all situations we all may encounter while using this service, but there will always be some things that are not covered. Those will be handled at ScribDen team’s discretion, and if something becomes a common issue or concern, we will update the ScribDen Code of Conduct to include it. If we see something that we feel is inappropriate or harmful to the ScribDen community, we do reserve the right to take appropriate actions for the overall health and quality of the ScribDen community. This includes things that are not specifically mentioned in the ScribDen Code of Conduct. If ever in doubt, please remember to be civil, constructive, and respectful at all times while using ScribDen.");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 84, filename: "views/app/ruleset.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 84, filename: jade_debug[0].filename });
buf.push("We monitor the site on a regular basis, not only to read your feedback, ideas, and suggestions, and interact with you, but also to ensure that our community is a civil, constructive, and safe place for everyone.");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 86, filename: "views/app/ruleset.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 86, filename: jade_debug[0].filename });
buf.push("The ScribDen Code of Conduct is intended to be your guide for all activity and interactions within the ScribDen community - we ask that you please try your best to abide by it. In the event that you violate the Code of Conduct, or if we simply have questions about something you have posted, we will always try to contact you first.");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 88, filename: "views/app/ruleset.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 88, filename: jade_debug[0].filename });
buf.push("Enforcement and application of the ScribDen Code of Conduct will be at the sole discretion of ScribDen, and authorized members of the ScribDen team. Material that is deemed offensive, illegal, or inappropriate in any way will be removed at the sole discretion of ScribDen. Please be aware that violating the ScribDen Code of Conduct can lead to disciplinary action, including, but not limited to, temporary suspension, banning, and the permanent closure of your ScribDen account, if the circumstances warrant it.");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift({ lineno: 90, filename: "views/app/ruleset.jade" });
buf.push("<section>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 91, filename: "views/app/ruleset.jade" });
buf.push("<h2 class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 91, filename: jade_debug[0].filename });
buf.push("Section II");
jade_debug.shift();
jade_debug.shift();
buf.push("</h2>");
jade_debug.shift();
jade_debug.unshift({ lineno: 93, filename: "views/app/ruleset.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 94, filename: "views/app/ruleset.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 94, filename: jade_debug[0].filename });
buf.push("Be Constructive:");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 95, filename: "views/app/ruleset.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 95, filename: jade_debug[0].filename });
buf.push(" When commenting on submitted media, including but not limited to artwork and web links, please try to be constructive in your criticism or balance criticism with praise. Comments that are excessively insulting or vulgar are not allowed.");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 97, filename: "views/app/ruleset.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 98, filename: "views/app/ruleset.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 98, filename: jade_debug[0].filename });
buf.push("No spam:");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 99, filename: "views/app/ruleset.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 99, filename: jade_debug[0].filename });
buf.push(" Members are encouraged to stay on topic and be relevant to the content of the thread. Posts that are nonsensical or irrelevant to the thread topic detract from the dialogue and are not allowed.");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 101, filename: "views/app/ruleset.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 102, filename: "views/app/ruleset.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 102, filename: jade_debug[0].filename });
buf.push("Rude and Insulting Comments:");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 103, filename: "views/app/ruleset.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 103, filename: jade_debug[0].filename });
buf.push(" We do not allow members to resort to rude comments and insults. This goes for rude comments and insults directed at other community members and ScribDen employees alike.");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift({ lineno: 105, filename: "views/app/ruleset.jade" });
buf.push("<section>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 106, filename: "views/app/ruleset.jade" });
buf.push("<h2 class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 106, filename: jade_debug[0].filename });
buf.push("Section III");
jade_debug.shift();
jade_debug.shift();
buf.push("</h2>");
jade_debug.shift();
jade_debug.unshift({ lineno: 108, filename: "views/app/ruleset.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 109, filename: "views/app/ruleset.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 109, filename: jade_debug[0].filename });
buf.push("Bashing and Slanderous Comments:");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 110, filename: "views/app/ruleset.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 110, filename: jade_debug[0].filename });
buf.push(" We do not permit the bashing of individuals, groups, or other companies.");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 112, filename: "views/app/ruleset.jade" });
buf.push("<p class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 113, filename: "views/app/ruleset.jade" });
buf.push("<strong>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 113, filename: jade_debug[0].filename });
buf.push("Trolling or Baiting:");
jade_debug.shift();
jade_debug.shift();
buf.push("</strong>");
jade_debug.shift();
jade_debug.unshift({ lineno: 114, filename: "views/app/ruleset.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 114, filename: jade_debug[0].filename });
buf.push(" The act of trolling is defined as something that is created for the intent to provoke conflict, shock others, or to elicit a strong negative or emotional reaction. It’s okay and very normal to disagree with others, and even to debate, but provoking conflict, baiting, inciting, mocking, etc. is never acceptable. If you do not have something constructive or meaningful to add to a discussion, we strongly recommend you refrain from posting in that thread and find another discussion to participate in instead. It is also not constructive or helpful to publicly call out others and accuse them of trolling or call them a troll - please refrain from doing so. If you genuinely believe someone is trolling, be proactive: report the post or thread and leave it at that.");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.shift();
buf.push("</article>");
jade_debug.shift();
jade_debug.shift();
buf.push("</main>");
jade_debug.shift();
jade_debug.shift();}.call(this,"require" in locals_for_with?locals_for_with.require:typeof require!=="undefined"?require:undefined,"undefined" in locals_for_with?locals_for_with.undefined:typeof undefined!=="undefined"?undefined:undefined));;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade_debug[0].filename, jade_debug[0].lineno, "include ../partials/generic_header\nmain.sd-o-main\n  include ../partials/flash\n  article.sd-o-frame-content\n    p.sd-t-wire Below is a brief explanation of our community rules and expectations for specific topics and situations. If you have any questions about our Community Code of Conduct, please email us at hexelberrystudios@gmail.com.\n\n    section.sd-u-content-padding--top-bottom\n      p.sd-t-wire\n        span For the\n        strong  Standard\n        span  ruleset, Section I applies.\n      p.sd-t-wire\n        span For the\n        strong  Moderate\n        span  ruleset, Sections I and II apply.\n      p.sd-t-wire\n        span For the\n        strong  Strict\n        span  ruleset, Sections I, II, and III apply.\n    \n    section\n      h2.sd-t-wire Section I\n      \n      p.sd-t-wire\n        strong Abusive Language and Disruptive Behavior:\n        span  We do not tolerate abusive or disruptive behavior on ScribDen. This goes for abusive and disruptive comments and behavior that is directed at employees and members alike. Posts that are excessively vulgar, insulting, explicit, or hateful may be removed. Please remember to be respectful and constructive at all times, and help us maintain a friendly and welcoming atmosphere for all.\n  \n      p.sd-t-wire\n        strong Conspiracy Theories and Misinformation:\n        span  We do not tolerate the deliberate and malicious spreading of false information. This does not include honest mistakes; rather, this rule pertains to those who go out of their way to spread harmful or malicious rumors about others, including but not limited to members, companies, or public figures.\n  \n      p.sd-t-wire\n        strong No Pirating:\n        span  Requesting or sharing material you do not own the copyright to or have permission to share (such as music, software, or art) is not permitted.\n  \n      p.sd-t-wire\n        strong No Stalking:\n        span  Persistent harassment of an individual or group of individuals against their wishes is not permitted. If someone asks you to stop, please leave them alone.\n  \n      p.sd-t-wire\n        strong Demands and Threats:\n        span  Concerns and requests may be made without needing to resort to demands and threats. We believe they are not constructive. Threats of real-life violence, in particular, are something we take very seriously and do not tolerate.\n  \n      p.sd-t-wire\n        strong Deliberately Disobeying a ScribDen Employee:\n        span  Deliberately disobeying a request or action by a  ScribDen employee, is not permitted at any time. As an example, if we close a thread you created and leave an explanation stating why it was closed, you may not re-create the thread.\n  \n      p.sd-t-wire\n        strong Discussing Disciplinary Actions:\n        span  If you ever have questions or concerns about a disciplinary action or decision a moderator has made on the forums, or wish to appeal an infraction you’ve received, we ask that you please contact us at hexelberrystudios@gmail.com to do so. Please specify that you are contacting about a forum-related inquiry or appeal. We are happy to discuss and review specific moderation-related actions with you, but we do not allow discussion of any moderation actions or decisions on our forums.\n  \n      p.sd-t-wire\n        strong Flaming:\n        span  It’s okay to disagree and debate, but we do ask that you keep all disagreements civil, constructive, and on-topic. If a discussion gets heated and turns into a debate, remember that you should stick to debating the post and/or thread topic. It is never appropriate to resort to personal comments or jabs about those participating in the thread discussion.\n  \n      p.sd-t-wire\n        strong Hate Speech:\n        span  We take the use of hate speech very seriously, and have a zero tolerance policy. Our definition of hate speech is prejudice or hateful comments, slurs, or statements that promote violence or intolerance toward others because of the following: Race, Color, National Origin, Gender, Age, Disability, Sexual Orientation, Lifestyle, and any other personally identifying factors.\n  \n      p.sd-t-wire\n        strong Impersonation:\n        span  We do not tolerate impersonation of real, living or dead individuals. Impersonation includes using a display name, photos, posts, or any other material with the intent to fool people into believing you are a ScribDen employee, another community member, a celebrity, or anyone else you are not. This does not apply to roleplaying fictional characters, although we prefer that you limit the impersonation of fictional characters to roleplaying threads only.\n  \n      p.sd-t-wire\n        strong Malicious Links:\n        span  We do not tolerate the posting of malicious links on our forums, for any reason. This includes but is not limited to links to key-loggers, browser hijackers, or phishing scams.\n  \n      p.sd-t-wire\n        strong Names in Thread Descriptions:\n        span  Please refrain from placing the names of ScribDen employees or members in your thread descriptions. Directing a thread at a specific individual, or otherwise using a thread to call someone out, is not considered constructive.\n  \n      p.sd-t-wire\n        strong Personal Information:\n        span  For the sake of your own identity protection and personal privacy, we ask that you please do not share any personal information in ScribDen. This also goes for sharing another member’s personal information.\n  \n      p.sd-t-wire\n        strong Thread Bumping:\n        span  Please refrain from replying to threads for the sole purpose of “bumping” them. This is considered to be a form of spam because it does not add to the discussion in a constructive or meaningful way. We understand that everyone would like to keep their discussion active and visible, but we encourage you to strive for meaningful and constructive posts instead of posts that consist of nothing more than “bump.”\n  \n      p.sd-t-wire\n        strong Other Cases:\n        span  The ScribDen Code of Conduct includes almost all situations we all may encounter while using this service, but there will always be some things that are not covered. Those will be handled at ScribDen team’s discretion, and if something becomes a common issue or concern, we will update the ScribDen Code of Conduct to include it. If we see something that we feel is inappropriate or harmful to the ScribDen community, we do reserve the right to take appropriate actions for the overall health and quality of the ScribDen community. This includes things that are not specifically mentioned in the ScribDen Code of Conduct. If ever in doubt, please remember to be civil, constructive, and respectful at all times while using ScribDen.\n  \n      p.sd-t-wire We monitor the site on a regular basis, not only to read your feedback, ideas, and suggestions, and interact with you, but also to ensure that our community is a civil, constructive, and safe place for everyone.\n  \n      p.sd-t-wire The ScribDen Code of Conduct is intended to be your guide for all activity and interactions within the ScribDen community - we ask that you please try your best to abide by it. In the event that you violate the Code of Conduct, or if we simply have questions about something you have posted, we will always try to contact you first.\n  \n      p.sd-t-wire Enforcement and application of the ScribDen Code of Conduct will be at the sole discretion of ScribDen, and authorized members of the ScribDen team. Material that is deemed offensive, illegal, or inappropriate in any way will be removed at the sole discretion of ScribDen. Please be aware that violating the ScribDen Code of Conduct can lead to disciplinary action, including, but not limited to, temporary suspension, banning, and the permanent closure of your ScribDen account, if the circumstances warrant it.\n      \n    section\n      h2.sd-t-wire Section II\n      \n      p.sd-t-wire\n        strong Be Constructive:\n        span  When commenting on submitted media, including but not limited to artwork and web links, please try to be constructive in your criticism or balance criticism with praise. Comments that are excessively insulting or vulgar are not allowed.\n  \n      p.sd-t-wire\n        strong No spam:\n        span  Members are encouraged to stay on topic and be relevant to the content of the thread. Posts that are nonsensical or irrelevant to the thread topic detract from the dialogue and are not allowed.\n  \n      p.sd-t-wire\n        strong Rude and Insulting Comments:\n        span  We do not allow members to resort to rude comments and insults. This goes for rude comments and insults directed at other community members and ScribDen employees alike.\n    \n    section\n      h2.sd-t-wire Section III\n      \n      p.sd-t-wire\n        strong Bashing and Slanderous Comments:\n        span  We do not permit the bashing of individuals, groups, or other companies.\n  \n      p.sd-t-wire\n        strong Trolling or Baiting:\n        span  The act of trolling is defined as something that is created for the intent to provoke conflict, shock others, or to elicit a strong negative or emotional reaction. It’s okay and very normal to disagree with others, and even to debate, but provoking conflict, baiting, inciting, mocking, etc. is never acceptable. If you do not have something constructive or meaningful to add to a discussion, we strongly recommend you refrain from posting in that thread and find another discussion to participate in instead. It is also not constructive or helpful to publicly call out others and accuse them of trolling or call them a troll - please refrain from doing so. If you genuinely believe someone is trolling, be proactive: report the post or thread and leave it at that.");
}
}