var jade = require("jadum/runtime");
module.exports = function settings(locals) {
var jade_debug = [{ lineno: 1, filename: "views/app/settings.jade" }];
try {
var buf = [];
var jade_mixins = {};
var jade_interp;
;var locals_for_with = (locals || {});(function (require, undefined, userId) {
jade_debug.unshift({ lineno: 0, filename: "views/app/settings.jade" });
jade_debug.unshift({ lineno: 1, filename: "views/app/settings.jade" });
buf.push(require("../partials/app_header").call(this, locals));
jade_debug.shift();
jade_debug.unshift({ lineno: 2, filename: "views/app/settings.jade" });
buf.push("<main class=\"sd-o-main sd-o-frame-content\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: undefined, filename: "views/app/settings.jade" });
buf.push(require("../partials/flash").call(this, locals));
jade_debug.shift();
jade_debug.unshift({ lineno: 4, filename: "views/app/settings.jade" });
if ( userId)
{
jade_debug.unshift({ lineno: 5, filename: "views/app/settings.jade" });
jade_debug.unshift({ lineno: 5, filename: "views/app/settings.jade" });
buf.push("<h2>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 5, filename: jade_debug[0].filename });
buf.push("Settings");
jade_debug.shift();
jade_debug.shift();
buf.push("</h2>");
jade_debug.shift();
jade_debug.unshift({ lineno: 6, filename: "views/app/settings.jade" });
buf.push("<form name=\"updateUserInfoForm\" method=\"post\" action=\"api/user\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 7, filename: "views/app/settings.jade" });
buf.push("<label for=\"profilePic\" class=\"sd-t-wire sd-u-display--block\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 7, filename: jade_debug[0].filename });
buf.push("Change your profile pic:");
jade_debug.shift();
jade_debug.shift();
buf.push("</label>");
jade_debug.shift();
jade_debug.unshift({ lineno: 8, filename: "views/app/settings.jade" });
buf.push("<input type=\"file\" id=\"profilePic\" name=\"profilePic\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 9, filename: "views/app/settings.jade" });
buf.push("<button type=\"submit\" class=\"sd-c-btn sd-t-wire sd-t-wire-hover sd-t-wire--field\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 9, filename: jade_debug[0].filename });
buf.push("Update");
jade_debug.shift();
jade_debug.shift();
buf.push("</button>");
jade_debug.shift();
jade_debug.shift();
buf.push("</form>");
jade_debug.shift();
jade_debug.unshift({ lineno: 10, filename: "views/app/settings.jade" });
buf.push("<a href=\"/api/user/logout\" class=\"sd-t-wire sd-u-content-padding--top-bottom\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 10, filename: jade_debug[0].filename });
buf.push("Logout");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.unshift({ lineno: 11, filename: "views/app/settings.jade" });
buf.push("<h2>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 11, filename: jade_debug[0].filename });
buf.push("Donations");
jade_debug.shift();
jade_debug.shift();
buf.push("</h2>");
jade_debug.shift();
jade_debug.unshift({ lineno: 12, filename: "views/app/settings.jade" });
buf.push("<form name=\"donateForm\" action=\"https://www.paypal.com/cgi-bin/webscr\" method=\"post\" target=\"_top\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 13, filename: "views/app/settings.jade" });
buf.push("<input type=\"hidden\" name=\"cmd\" value=\"_xclick-subscriptions\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 14, filename: "views/app/settings.jade" });
buf.push("<input type=\"hidden\" name=\"business\" value=\"B863WBL585QR8\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 15, filename: "views/app/settings.jade" });
buf.push("<input type=\"hidden\" name=\"lc\" value=\"US\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 16, filename: "views/app/settings.jade" });
buf.push("<input type=\"hidden\" name=\"item_name\" value=\"Donate Monthly\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 17, filename: "views/app/settings.jade" });
buf.push("<input type=\"hidden\" name=\"no_note\" value=\"1\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 18, filename: "views/app/settings.jade" });
buf.push("<input type=\"hidden\" name=\"no_shipping\" value=\"1\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 19, filename: "views/app/settings.jade" });
buf.push("<input type=\"hidden\" name=\"src\" value=\"1\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 20, filename: "views/app/settings.jade" });
buf.push("<input type=\"hidden\" name=\"a3\" value=\"1.00\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 21, filename: "views/app/settings.jade" });
buf.push("<input type=\"hidden\" name=\"p3\" value=\"1\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 22, filename: "views/app/settings.jade" });
buf.push("<input type=\"hidden\" name=\"t3\" value=\"M\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 23, filename: "views/app/settings.jade" });
buf.push("<input type=\"hidden\" name=\"currency_code\" value=\"USD\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 24, filename: "views/app/settings.jade" });
buf.push("<input type=\"hidden\" name=\"bn\" value=\"PP-SubscriptionsBF:btn_subscribeCC_LG.gif:NonHosted\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 25, filename: "views/app/settings.jade" });
buf.push("<p>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 25, filename: jade_debug[0].filename });
buf.push("ScribDen runs entirely on our user's donations. We depend on you to help us keep this site running.");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 26, filename: "views/app/settings.jade" });
buf.push("<p>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 26, filename: jade_debug[0].filename });
buf.push("If you wish to contribute, please enter an amount below.");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 27, filename: "views/app/settings.jade" });
buf.push("<p class=\"sd-u-align--center\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 28, filename: "views/app/settings.jade" });
buf.push("<input type=\"text\" name=\"a3\" maxlength=\"200\" required=\"required\" class=\"sd-t-wire sd-t-wire--field\"/>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 29, filename: "views/app/settings.jade" });
buf.push("<p class=\"sd-u-align--center\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 30, filename: "views/app/settings.jade" });
buf.push("<input type=\"image\" src=\"https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif\" border=\"0\" name=\"submit\" alt=\"PayPal - The safer, easier way to pay online!\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 31, filename: "views/app/settings.jade" });
buf.push("<img alt=\"\" border=\"0\" src=\"https://www.paypalobjects.com/en_US/i/scr/pixel.gif\" width=\"1\" height=\"1\"/>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 32, filename: "views/app/settings.jade" });
buf.push("<p>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 33, filename: "views/app/settings.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 33, filename: jade_debug[0].filename });
buf.push("This amount will be billed monthly, and can be cancelled at any time, even after just the first month. Just email us at ");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 34, filename: "views/app/settings.jade" });
buf.push("<a href=\"mailto:support@scribden.com?subject=&quot;Cancel Subscription&quot;\" class=\"sd-t-wire sd-t-link\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 34, filename: jade_debug[0].filename });
buf.push("support@scribden.com.");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 35, filename: "views/app/settings.jade" });
buf.push("<p>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 35, filename: jade_debug[0].filename });
buf.push("Regardless of whether or not you decide to contribute, you are a part of what makes ScribDen great! Thank you so much for being here! And if you already contribute, thank you! We really appreciate your help!");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</form>");
jade_debug.shift();
jade_debug.shift();
}
else
{
jade_debug.unshift({ lineno: 37, filename: "views/app/settings.jade" });
jade_debug.unshift({ lineno: 37, filename: "views/app/settings.jade" });
buf.push("<p class=\"sd-t-wire sd-u-content-padding--sides\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 38, filename: "views/app/settings.jade" });
buf.push("<a href=\"/register\" class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 38, filename: jade_debug[0].filename });
buf.push("Register");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.unshift({ lineno: 39, filename: "views/app/settings.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 39, filename: jade_debug[0].filename });
buf.push(" or ");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 40, filename: "views/app/settings.jade" });
buf.push("<a href=\"/\" class=\"sd-t-wire\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 40, filename: jade_debug[0].filename });
buf.push("login");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.unshift({ lineno: 41, filename: "views/app/settings.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 41, filename: jade_debug[0].filename });
buf.push(" to update your account settings.");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
}
jade_debug.shift();
jade_debug.shift();
buf.push("</main>");
jade_debug.shift();
jade_debug.shift();}.call(this,"require" in locals_for_with?locals_for_with.require:typeof require!=="undefined"?require:undefined,"undefined" in locals_for_with?locals_for_with.undefined:typeof undefined!=="undefined"?undefined:undefined,"userId" in locals_for_with?locals_for_with.userId:typeof userId!=="undefined"?userId:undefined));;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade_debug[0].filename, jade_debug[0].lineno, "include ../partials/app_header\nmain.sd-o-main.sd-o-frame-content\n  include ../partials/flash\n  if userId\n    h2 Settings\n    form(name='updateUserInfoForm' method='post' action='api/user')\n      label.sd-t-wire.sd-u-display--block(for='profilePic') Change your profile pic:\n      input(type='file' id='profilePic' name='profilePic')\n      button.sd-c-btn.sd-t-wire.sd-t-wire-hover.sd-t-wire--field(type='submit') Update\n    a.sd-t-wire.sd-u-content-padding--top-bottom(href='/api/user/logout') Logout\n    h2 Donations\n    form(name='donateForm' action='https://www.paypal.com/cgi-bin/webscr' method='post' target='_top')\n      input(type='hidden' name='cmd' value='_xclick-subscriptions')\n      input(type='hidden' name='business' value='B863WBL585QR8')\n      input(type='hidden' name='lc' value='US')\n      input(type='hidden' name='item_name' value='Donate Monthly')\n      input(type='hidden' name='no_note' value='1')\n      input(type='hidden' name='no_shipping' value='1')\n      input(type='hidden' name='src' value='1')\n      input(type='hidden' name='a3' value='1.00')\n      input(type='hidden' name='p3' value='1')\n      input(type='hidden' name='t3' value='M')\n      input(type='hidden' name='currency_code' value='USD')\n      input(type='hidden' name='bn' value='PP-SubscriptionsBF:btn_subscribeCC_LG.gif:NonHosted')\n      p ScribDen runs entirely on our user's donations. We depend on you to help us keep this site running.\n      p If you wish to contribute, please enter an amount below.\n      p.sd-u-align--center\n        input.sd-t-wire.sd-t-wire--field(type='text' name='a3' maxlength='200' required)\n      p.sd-u-align--center\n        input(type='image' src='https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif' border='0' name='submit' alt='PayPal - The safer, easier way to pay online!')\n        img(alt='' border='0' src='https://www.paypalobjects.com/en_US/i/scr/pixel.gif' width='1' height='1')\n      p\n        span This amount will be billed monthly, and can be cancelled at any time, even after just the first month. Just email us at \n        a.sd-t-wire.sd-t-link(href='mailto:support@scribden.com?subject=\"Cancel Subscription\"') support@scribden.com.\n      p Regardless of whether or not you decide to contribute, you are a part of what makes ScribDen great! Thank you so much for being here! And if you already contribute, thank you! We really appreciate your help!\n  else\n    p.sd-t-wire.sd-u-content-padding--sides\n        a(href='/register').sd-t-wire Register\n        span  or \n        a(href='/').sd-t-wire login\n        span  to update your account settings.");
}
}